#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod c_dai_delegate;
pub mod c_delegate_interface;
pub mod c_delegation_storage;
pub mod c_delegator_interface;
pub mod c_erc_20;
pub mod c_erc_20_delegate;
pub mod c_erc_20_delegator;
pub mod c_erc_20_immutable;
pub mod c_erc_20_interface;
pub mod c_erc_20_storage;
pub mod c_ether;
pub mod c_token;
pub mod c_token_interface;
pub mod c_token_storage;
pub mod careful_math;
pub mod comp;
pub mod comp_interface;
pub mod compound_lens;
pub mod comptroller;
pub mod comptroller_error_reporter;
pub mod comptroller_g1;
pub mod comptroller_g2;
pub mod comptroller_g3;
pub mod comptroller_interface;
pub mod comptroller_lens_interface;
pub mod comptroller_v1_storage;
pub mod comptroller_v2_storage;
pub mod comptroller_v3_storage;
pub mod dai_interest_rate_model_v2;
pub mod dai_join_like;
pub mod eip20_interface;
pub mod eip20_non_standard_interface;
pub mod exponential;
pub mod gem_like;
pub mod governor_alpha;
pub mod interest_rate_model;
pub mod jug_like;
pub mod jump_rate_model;
pub mod maximillion;
pub mod pot_like;
pub mod price_oracle;
pub mod price_oracle_proxy;
pub mod reservoir;
pub mod safe_math;
pub mod simple_price_oracle;
pub mod timelock;
pub mod timelock_interface;
pub mod token_error_reporter;
pub mod unitroller;
pub mod unitroller_admin_storage;
pub mod v1_price_oracle_interface;
pub mod vat_like;
pub mod white_paper_interest_rate_model;
