[package]
name = "uniswap-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }
serde_json = "1.0"

[build-dependencies]
foundry-binder = { path = "../../foundry/binder" }